# Generated by Django 5.2.3 on 2025-07-22 05:53

import django.core.validators
import django.db.models.deletion
import materials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student'),
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-uploaded_at'], 'permissions': [('can_download_material', 'Can download materials')]},
        ),
        migrations.AddField(
            model_name='material',
            name='allowed_roles',
            field=models.CharField(default='student,teacher', max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='material',
            name='uploaded_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(default='', upload_to=materials.models.material_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx']), materials.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(default='Untitled Material', max_length=200),
        ),
    ]
