# Generated by Django 5.2.3 on 2025-07-22 02:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_due_date_submission_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, help_text="Teacher's feedback"),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.PositiveIntegerField(blank=True, help_text='Score out of max score', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('graded', 'Graded'), ('late', 'Late Submission')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(default='', help_text='Detailed description of the assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, default='', help_text='Allowed formats: PDF, DOC, DOCX', null=True, upload_to='assignments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='', help_text='Title of the assignment', max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (97-100)'), ('A', 'A (93-96)'), ('A-', 'A- (90-92)'), ('B+', 'B+ (87-89)'), ('B', 'B (83-86)'), ('B-', 'B- (80-82)'), ('C+', 'C+ (77-79)'), ('C', 'C (73-76)'), ('C-', 'C- (70-72)'), ('D', 'D (60-69)')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])]),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='assignments_due_dat_7a9bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_at'], name='assignments_created_300492_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='assignments_submitt_1a547c_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='assignments_status_d82c9c_idx'),
        ),
    ]
